# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: galbot/navigation_proto/odometry.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from galbot.core_proto import header_pb2 as galbot_dot_core__proto_dot_header__pb2
from galbot.spatial_proto import pose_pb2 as galbot_dot_spatial__proto_dot_pose__pb2
from galbot.spatial_proto import twist_pb2 as galbot_dot_spatial__proto_dot_twist__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='galbot/navigation_proto/odometry.proto',
  package='galbot.navigation_proto',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&galbot/navigation_proto/odometry.proto\x12\x17galbot.navigation_proto\x1a\x1egalbot/core_proto/header.proto\x1a\x1fgalbot/spatial_proto/pose.proto\x1a galbot/spatial_proto/twist.proto\"\xa9\x01\n\x08Odometry\x12)\n\x06header\x18\x01 \x01(\x0b\x32\x19.galbot.core_proto.Header\x12\x16\n\x0e\x63hild_frame_id\x18\x02 \x01(\t\x12+\n\x04pose\x18\x03 \x01(\x0b\x32\x1d.galbot.spatial_proto.PoseMsg\x12-\n\x05twist\x18\x04 \x01(\x0b\x32\x1e.galbot.spatial_proto.TwistMsgb\x06proto3'
  ,
  dependencies=[galbot_dot_core__proto_dot_header__pb2.DESCRIPTOR,galbot_dot_spatial__proto_dot_pose__pb2.DESCRIPTOR,galbot_dot_spatial__proto_dot_twist__pb2.DESCRIPTOR,])




_ODOMETRY = _descriptor.Descriptor(
  name='Odometry',
  full_name='galbot.navigation_proto.Odometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='header', full_name='galbot.navigation_proto.Odometry.header', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='child_frame_id', full_name='galbot.navigation_proto.Odometry.child_frame_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pose', full_name='galbot.navigation_proto.Odometry.pose', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='twist', full_name='galbot.navigation_proto.Odometry.twist', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=167,
  serialized_end=336,
)

_ODOMETRY.fields_by_name['header'].message_type = galbot_dot_core__proto_dot_header__pb2._HEADER
_ODOMETRY.fields_by_name['pose'].message_type = galbot_dot_spatial__proto_dot_pose__pb2._POSEMSG
_ODOMETRY.fields_by_name['twist'].message_type = galbot_dot_spatial__proto_dot_twist__pb2._TWISTMSG
DESCRIPTOR.message_types_by_name['Odometry'] = _ODOMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Odometry = _reflection.GeneratedProtocolMessageType('Odometry', (_message.Message,), {
  'DESCRIPTOR' : _ODOMETRY,
  '__module__' : 'galbot.navigation_proto.odometry_pb2'
  # @@protoc_insertion_point(class_scope:galbot.navigation_proto.Odometry)
  })
_sym_db.RegisterMessage(Odometry)


# @@protoc_insertion_point(module_scope)
