import os
import shutil
import json

os.chdir(os.path.dirname(os.path.abspath(__file__)))


TEMPLATE_ROOT = "../templates"
FOLLOWER_TPL = os.path.join(TEMPLATE_ROOT, "follower")
LEADER_TPL   = os.path.join(TEMPLATE_ROOT, "leader")

AUTO_HEADER = "# Auto-generated by generate_ros2.py\n\n"




def ensure_dir(path: str):
    os.makedirs(path, exist_ok=True)


def load_template(path: str):
    return open(path, "r", encoding="utf-8").read() if os.path.isfile(path) else None


def write_file(path: str, content: str):
    ensure_dir(os.path.dirname(path))
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def generate_file(path: str, tpl_path: str, fallback_generator):
    """
    旧版逻辑：如果有模板文件就直接写模板，否则用 fallback_generator() 生成内容
    """
    tpl = load_template(tpl_path)
    if tpl:
        write_file(path, tpl)
    else:
        write_file(path, fallback_generator())


def fill_template(template_str: str, data: dict) -> str:
    """
    非侵入式模板替换：
    模板中如果写了 {{key}} 就替换，否则保持不动
    """
    result = template_str
    for k, v in data.items():
        placeholder = "{{" + k + "}}"
        result = result.replace(placeholder, str(v))
    return result


def generate_file_with_dict(path: str, tpl_path: str, data: dict, fallback_generator):
    """
    带字典的模板生成：
    - 如果有模板：读取模板 → 用 data 做 {{key}} 替换
    - 否则：调用 fallback_generator(data) 生成代码
    """
    tpl = load_template(tpl_path)
    if tpl:
        content = fill_template(tpl, data)
    else:
        content = fallback_generator(data)
    write_file(path, content)



def gen_lerobot_follower_init(robot_name: str) -> str:
    pkg = f"robodriver_robot_{robot_name}_follower_ros2"
    return f"from {pkg} import *\n"


def gen_follower_calibrate() -> str:
    return AUTO_HEADER + "# TODO\n"


def gen_follower_config_py(robot_name: str, json_data: dict) -> str:
    """
    自动生成 follower 端 config.py
    仅使用 group == 'observation' 的组件
    """
    class_suffix = "FollowerRos2"
    subclass_name = f"{robot_name}_follower_ros2"
    class_name = f"{robot_name.upper().replace('-', '').replace('_','')}{class_suffix}RobotConfig"

    motors_dict = {}
    cameras_dict = {}

    # ----------- 解析 motors（只取 observation） ----------- 
    for comp in json_data["components"]:
        if comp["params"].get("group") != "observation":
            continue

        outputs_info = comp.get("outputs_info", {})
        for _out_name, out_cfg in outputs_info.items():
            motors = out_cfg.get("motors", {})
            for motor_name, (motor_id, motor_model) in motors.items():
                motors_dict[motor_name] = (motor_id, motor_model)

    # ----------- 构造 motors 文本 ----------- 
    motors_code_lines = ["            {"]
    DEFAULT_MODEL = "sts3215"

    for name, (mid, model) in motors_dict.items():
        model = model or DEFAULT_MODEL
        motors_code_lines.append(
            f"                \"{name}\": Motor({mid}, \"{model}\", norm_mode_body),"
        )
    motors_code_lines.append("            }")

    # ----------- 解析 cameras（只取 observation） ----------- 
    cam_index = 0
    for comp in json_data["components"]:
        if comp["params"].get("group") != "observation":
            continue

        if "image" in comp["params"].get("output", []):
            cid = comp["id"]
            p = comp["params"]
            cameras_dict[cid] = {
                "index": cam_index,
                "fps": p.get("period", 30),
                "width": p.get("width", 640),
                "height": p.get("height", 480)
            }
            cam_index += 1

    cameras_code_lines = ["            {"]
    for cid, c in cameras_dict.items():
        cameras_code_lines.append(
            f"                \"{cid}\": OpenCVCameraConfig(index_or_path={c['index']}, "
            f"fps={c['fps']}, width={c['width']}, height={c['height']}),"
        )
    cameras_code_lines.append("            }")

    use_videos = json_data.get("use_videos", False)

    return f'''\
from dataclasses import dataclass, field
from typing import Dict
from lerobot.robots.config import RobotConfig
from lerobot.cameras import CameraConfig
from lerobot.cameras.opencv import OpenCVCameraConfig
from lerobot.motors import Motor, MotorNormMode

@RobotConfig.register_subclass("{subclass_name}")
@dataclass
class {class_name}(RobotConfig):
    use_degrees = True
    norm_mode_body = MotorNormMode.DEGREES if use_degrees else MotorNormMode.RANGE_M100_100

    motors: Dict[str, Motor] = field(
        default_factory=lambda norm_mode_body=norm_mode_body: 
{chr(10).join(motors_code_lines)}
    )

    cameras: Dict[str, CameraConfig] = field(
        default_factory=lambda: 
{chr(10).join(cameras_code_lines)}
    )

    use_videos: bool = {use_videos}

    microphones: Dict[str, int] = field(default_factory=lambda: {{}})
'''


# ============================================================
# leader (操作者端) 简单文件：__init__ / calibrate / config
# ============================================================

def gen_lerobot_leader_init(robot_name: str) -> str:
    pkg = f"robodriver_teleoperator_{robot_name}_leader_ros2"
    return f"from {pkg} import *\n"


def gen_leader_calibrate() -> str:
    return AUTO_HEADER + "# TODO\n"


def gen_leader_config_py(robot_name: str, json_data: dict) -> str:
    """
    自动生成 leader 端 config.py
    仅使用 group == 'action' 的组件
    """
    class_suffix = "LeaderRos2"
    subclass_name = f"{robot_name}_leader_ros2"
    class_name = f"{robot_name.upper().replace('-', '').replace('_','')}{class_suffix}RobotConfig"

    motors_dict = {}
    cameras_dict = {}

    # ----------- 解析 motors（只取 action） ----------- 
    for comp in json_data["components"]:
        if comp["params"].get("group") != "action":
            continue

        outputs_info = comp.get("outputs_info", {})
        for _out_name, out_cfg in outputs_info.items():
            motors = out_cfg.get("motors", {})
            for motor_name, (motor_id, motor_model) in motors.items():
                motors_dict[motor_name] = (motor_id, motor_model)

    # ----------- 构造 motors 文本 ----------- 
    motors_code_lines = ["            {"]
    DEFAULT_MODEL = "sts3215"

    for name, (mid, model) in motors_dict.items():
        model = model or DEFAULT_MODEL
        motors_code_lines.append(
            f"                \"{name}\": Motor({mid}, \"{model}\", norm_mode_body),"
        )
    motors_code_lines.append("            }")

    # ----------- cameras（只取 action） ----------- 
    cam_index = 0
    for comp in json_data["components"]:
        if comp["params"].get("group") != "action":
            continue

        if "image" in comp["params"].get("output", []):
            cid = comp["id"]
            p = comp["params"]
            cameras_dict[cid] = {
                "index": cam_index,
                "fps": p.get("period", 30),
                "width": p.get("width", 640),
                "height": p.get("height", 480)
            }
            cam_index += 1

    cameras_code_lines = ["            {"]
    for cid, c in cameras_dict.items():
        cameras_code_lines.append(
            f"                \"{cid}\": OpenCVCameraConfig(index_or_path={c['index']}, "
            f"fps={c['fps']}, width={c['width']}, height={c['height']}),"
        )
    cameras_code_lines.append("            }")

    use_videos = json_data.get("use_videos", False)

    return f'''\
from dataclasses import dataclass, field
from typing import Dict
from lerobot.robots.config import RobotConfig
from lerobot.cameras import CameraConfig
from lerobot.cameras.opencv import OpenCVCameraConfig
from lerobot.motors import Motor, MotorNormMode

@RobotConfig.register_subclass("{subclass_name}")
@dataclass
class {class_name}(RobotConfig):
    use_degrees = True
    norm_mode_body = MotorNormMode.DEGREES if use_degrees else MotorNormMode.RANGE_M100_100

    motors: Dict[str, Motor] = field(
        default_factory=lambda norm_mode_body=norm_mode_body: 
{chr(10).join(motors_code_lines)}
    )

    cameras: Dict[str, CameraConfig] = field(
        default_factory=lambda: 
{chr(10).join(cameras_code_lines)}
    )

    use_videos: bool = {use_videos}

    microphones: Dict[str, int] = field(default_factory=lambda: {{}})
'''



def build_follower_node_dict(json_data):
    """
    输入 JSON（你的统一 config.json）
    输出 follower ROS2 node 所需 topic_dict
    """

    topic_dict = {}

    for comp in json_data["components"]:
        cid = comp["id"]
        params = comp["params"]

        entry = {
            "topic": params.get("topic", ""),
            "msgs": params.get("msg_type", ""),
        }

        if "joint_index" in params:
            entry["joint_index"] = params["joint_index"]

        if entry["msgs"] in ["sensor_msgs/Image", "sensor_msgs/CompressedImage"]:
            entry["encoding"] = params.get("encoding", "bgr8")
            entry["width"] = params.get("width")
            entry["height"] = params.get("height")

        topic_dict[cid] = entry

    for act in json_data.get("actions", []):
        topic_dict[act["id"]] = {
            "type": "publisher",
            "topic": act["topic"],
        }

    return topic_dict



def build_follower_robot_dict(json_data: dict, robot_name: str) -> dict:
    """
    从 JSON 配置中提取 follower robot 模板所需字段。
    这里只做“命名”和简单参数的组织，不做复杂推导。
    """

    # 基础前缀（和 config/status/node 命名保持一致）
    base = robot_name.upper().replace("-", "").replace("_", "")

    robot_class = f"{base}FollowerRos2Robot"
    config_class = f"{base}FollowerRos2RobotConfig"
    status_class = f"{base}FollowerRos2RobotStatus"
    node_class = f"{base}FollowerRos2RobotNode"

    # 被排除的相机，可以在 json 中自定义一个字段，例如:
    # "connect_excluded_cameras": ["image_pika_pose", ...]
    excluded_cameras = json_data.get("connect_excluded_cameras", [])

    # 最终字典（对应模板里的占位符）
    return {
        "robot_name": robot_name,
        "robot_class": robot_class,
        "config_class": config_class,
        "status_class": status_class,
        "node_class": node_class,
        "excluded_cameras": excluded_cameras,
    }



def build_follower_status_dict(robot_name: str, json_data: dict) -> dict:
    """
    构造 follower status.py 模板需要的上下文字典
    """

    base = robot_name.upper().replace("-", "").replace("_", "")
    class_name = f"{base}FollowerRos2RobotStatus"

    # 假设 JSON 中提供一个 "status" 字段专门包含状态参数
    status = json_data.get("status", {})

    # 组装 camera block
    camera_block_lines = []
    for cam in status.get("cameras", []):
        camera_block_lines.append(
            f"""                CameraInfo(
                    name="{cam['name']}",
                    chinese_name="{cam['chinese_name']}",
                    type="{cam['type']}",
                    width={cam['width']},
                    height={cam['height']},
                    is_connect={cam['is_connect']}
                ),"""
        )
    camera_block = "\n".join(camera_block_lines)

    # 组装 arm block
    arm_block_lines = []
    for arm in status.get("arms", []):
        arm_block_lines.append(
            f"""                ArmInfo(
                    name="{arm['name']}",
                    type="{arm['type']}",
                    start_pose={arm['start_pose']},
                    joint_p_limit={arm['joint_p_limit']},
                    joint_n_limit={arm['joint_n_limit']},
                    is_connect={arm['is_connect']}
                ),"""
        )
    arm_block = "\n".join(arm_block_lines)

    return {
        "REGISTRY_NAME": status.get("registry_name", f"{robot_name}_follower_ros2"),
        "CLASS_NAME": class_name,
        "DEVICE_NAME": status.get("device_name", robot_name.upper()),
        "DEVICE_BODY": status.get("device_body", robot_name.upper()),
        "END_TYPE": status.get("end_type", "Default"),
        "FPS": status.get("fps", 30),
        "CAMERA_BLOCK": camera_block,
        "ARM_BLOCK": arm_block,
    }



def build_leader_node_dict(robot_name: str, json_data: dict) -> dict:
    """
    从 json_data 构造 Leader Node 需要的所有占位符字典
    """

    # 类名：SO101LeaderRos2TeleoperatorNode
    NodeClass = (
        robot_name.upper().replace("-", "").replace("_", "")
        + "LeaderRos2TeleoperatorNode"
    )

    # ROS2 节点名：so101_leader_ros2_node
    node_name = f"{robot_name}_leader_ros2_node"

    # leader node 只需要 group=action 的组件，并且 msgs == JointState
    topic_dict = {}

    for comp in json_data.get("components", []):
        params = comp.get("params", {})

        if params.get("group") != "action":
            continue

        topic = params.get("topic", "")
        msg_type = params.get("msgs", "")

        # leader node 仅订阅关节
        if msg_type != "sensor_msgs/JointState":
            continue

        topic_dict[comp["id"]] = {
            "topic": topic,
            "msgs": msg_type,
            "joint_index": params.get("joint_index", []),
        }

    # 转成 JSON 文本，作为模板替换内容
    topic_dict_json = json.dumps(topic_dict, indent=4, ensure_ascii=False)

    return {
        "NodeClass": NodeClass,
        "node_name": node_name,
        "TOPIC_DICT_JSON": topic_dict_json,
    }


def build_leader_teleoperator_dict(robot_name: str, json_data: dict) -> dict:
    """
    构造 teleoperator.py 模板所需字典
    """

    base = robot_name.upper().replace("-", "").replace("_", "")

    return {
        "TeleoperatorClass": f"{base}LeaderRos2Teleoperator",
        "ConfigClass": f"{base}LeaderRos2TeleoperatorConfig",
        "StatusClass": f"{base}LeaderRos2TeleoperatorStatus",
        "NodeClass": f"{base}LeaderRos2TeleoperatorNode",
        "robot_name": robot_name,
    }


def build_leader_status_dict(robot_name: str, json_data: dict) -> dict:
    """
    构造用于渲染 leader/status.py 的上下文字典（context）
    """

    StatusClass = (
        robot_name.upper().replace("-", "").replace("_", "")
        + "LeaderRos2TeleoperatorStatus"
    )
    status_key = f"{robot_name}_leader_ros2"
    device_name = json_data.get("device_name", robot_name.upper())
    device_body = json_data.get("device_body", robot_name.upper())
    end_effector = json_data.get("end_effector", "Default")
    fps = json_data.get("fps", 30)

    # 构建 Arm 列表
    arms = []
    for comp in json_data.get("components", []):
        params = comp.get("params", {})
        if params.get("group") != "action":  # 只取 leader 的 arm
            continue

        arms.append({
            "name": comp["id"],
            "type": params.get("arm_type", ""),
            "start_pose": params.get("start_pose", []),
            "joint_p_limit": params.get("joint_p_limit", []),
            "joint_n_limit": params.get("joint_n_limit", []),
            "is_connect": False,  # 初始均 False
        })

    # Arm 信息字符串
    arm_lines = []
    for arm in arms:
        arm_lines.append(
            f'''                ArmInfo(
                    name="{arm['name']}",
                    type="{arm['type']}",
                    start_pose={arm['start_pose']},
                    joint_p_limit={arm['joint_p_limit']},
                    joint_n_limit={arm['joint_n_limit']},
                    is_connect={arm['is_connect']}
                ),'''
        )
    arm_block = "\n".join(arm_lines)

    return {
        "STATUS_KEY": status_key,
        "STATUS_CLASS": StatusClass,
        "DEVICE_NAME": device_name,
        "DEVICE_BODY": device_body,
        "END_EFFECTOR": end_effector,
        "FPS": fps,
        "ARM_INFOS": arm_block,
    }




def gen_follower_node_py(robot_name, node_dict):

    NodeClass = f"{robot_name.upper()}FollowerRos2RobotNode"
    node_name = f"{robot_name}_follower_ros2"

    # JSON 转字符串并缩进
    topic_dict_json = json.dumps(node_dict, indent=4)

    template_path = os.path.join(FOLLOWER_TPL, "node.py")
    template = load_template(template_path)

    if template is None:
        raise FileNotFoundError("Follower node 模板不存在")

    code = (
        template
        .replace("{{NodeClass}}", NodeClass)
        .replace("{{node_name}}", node_name)
        .replace("{{TOPIC_DICT_JSON}}", topic_dict_json)
    )

    return code



def gen_follower_robot_py(robot_dict: dict) -> str:
    """
    根据 follower robot 字典 + 模板生成最终 robot.py 源码字符串
    """

    template_path = os.path.join(FOLLOWER_TPL, "robot.py")
    template = load_template(template_path)
    if not template:
        raise FileNotFoundError(f"follower robot 模板不存在: {template_path}")

    code = (
        template
        .replace("{{RobotClass}}", robot_dict["robot_class"])
        .replace("{{ConfigClass}}", robot_dict["config_class"])
        .replace("{{StatusClass}}", robot_dict["status_class"])
        .replace("{{NodeClass}}", robot_dict["node_class"])
        .replace("{{robot_name}}", robot_dict["robot_name"])
        .replace("{{excluded_cameras}}", repr(robot_dict["excluded_cameras"]))
    )

    return code



def gen_follower_status_py(robot_name: str, json_data: dict) -> str:
    """
    渲染 follower status.py
    """

    ctx = build_follower_status_dict(robot_name, json_data)

    template_path = os.path.join(FOLLOWER_TPL, "status.py")
    template = load_template(template_path)
    if not template:
        raise FileNotFoundError(f"Follower status 模板不存在: {template_path}")

    # 替换所有占位符
    for key, value in ctx.items():
        template = template.replace(f"{{{{{key}}}}}", str(value))

    return template



def gen_leader_node_py(robot_name, json_data):
    """
    根据模板 + 字典生成 leader node.py
    """

    # 读模板
    tpl_path = os.path.join(LEADER_TPL, "node.py")
    template = load_template(tpl_path)

    if template is None:
        raise FileNotFoundError(f"Leader node 模板缺失: {tpl_path}")

    # 构造替换字典
    ctx = build_leader_node_dict(robot_name, json_data)

    # 依次替换所有 {{xxx}}
    for key, value in ctx.items():
        template = template.replace("{{" + key + "}}", value)

    return template



def gen_leader_teleoperator_py(robot_name: str, json_data: dict) -> str:
    """
    渲染 leader 端 teleoperator.py（从模板）
    """

    # 构造模板上下文字典
    ctx = build_leader_teleoperator_dict(robot_name, json_data)

    # 读取模板
    template_path = os.path.join(LEADER_TPL, "teleoperator.py")
    template = load_template(template_path)
    if not template:
        raise FileNotFoundError(f"Leader teleoperator 模板不存在: {template_path}")

    # 替换所有占位符
    for key, value in ctx.items():
        template = template.replace(f"{{{{{key}}}}}", str(value))

    return template



def gen_leader_status_py(robot_name: str, json_data: dict) -> str:
    context = build_leader_status_dict(robot_name, json_data)
    template_path = os.path.join(LEADER_TPL, "status.py")
    template = load_template(template_path)

    if template is None:
        raise FileNotFoundError(f"leader status 模板不存在: {template_path}")

    for key, value in context.items():
        template = template.replace("{{" + key + "}}", str(value))

    return template



# ============================================================
# 主生成逻辑
# ============================================================

def generate_ros2_project(json_path, output_root="./robots_out"):
    """主生成入口"""

    with open(json_path, "r", encoding="utf-8") as f:
        json_data = json.load(f)

    robot_name = os.path.splitext(os.path.basename(json_path))[0]

    # 顶层目录
    follower_root = os.path.join(output_root, f"robodriver-robot-{robot_name}-follower-ros2")
    leader_root   = os.path.join(output_root, f"robodriver-teleoperator-{robot_name}-leader-ros2")

    # 清空旧目录
    for d in (follower_root, leader_root):
        if os.path.exists(d):
            shutil.rmtree(d)

    follower_pkg_A = os.path.join(follower_root, f"lerobot_robot_{robot_name}_follower_ros2")
    follower_pkg_B = os.path.join(follower_root, f"robodriver_robot_{robot_name}_follower_ros2")

    leader_pkg_A = os.path.join(leader_root, f"lerobot_teleoperator_{robot_name}_leader_ros2")
    leader_pkg_B = os.path.join(leader_root, f"robodriver_teleoperator_{robot_name}_leader_ros2")

    for d in [follower_pkg_A, follower_pkg_B, leader_pkg_A, leader_pkg_B]:
        ensure_dir(d)

       # =============================
    # follower B 套件（不带模板字典的简单文件）
    # =============================
    generate_file(
        os.path.join(follower_pkg_B, "__init__.py"),
        os.path.join(FOLLOWER_TPL, "__init__.py"),
        lambda: gen_lerobot_follower_init(robot_name),
    )

    generate_file(
        os.path.join(follower_pkg_B, "calibrate.py"),
        os.path.join(FOLLOWER_TPL, "calibrate.py"),
        gen_follower_calibrate,
    )

    generate_file(
        os.path.join(follower_pkg_B, "config.py"),
        os.path.join(FOLLOWER_TPL, "config.py"),
        lambda: gen_follower_config_py(robot_name, json_data),
    )

    # =============================
    # follower B 套件（使用模板字典的 3 个文件）
    # =============================
    follower_node_ctx = build_follower_node_dict(json_data)
    generate_file_with_dict(
        os.path.join(follower_pkg_B, "node.py"),
        os.path.join(FOLLOWER_TPL, "node.py"),
        follower_node_ctx,
        lambda ctx: ""
    )

    follower_robot_ctx = build_follower_robot_dict(json_data, robot_name)
    generate_file_with_dict(
        os.path.join(follower_pkg_B, "robot.py"),
        os.path.join(FOLLOWER_TPL, "robot.py"),
        follower_robot_ctx,
        lambda ctx: ""
    )

    follower_status_ctx = build_follower_status_dict(robot_name, json_data)
    generate_file_with_dict(
        os.path.join(follower_pkg_B, "status.py"),
        os.path.join(FOLLOWER_TPL, "status.py"),
        follower_status_ctx,
        lambda ctx: ""
    )

    generate_file(
        os.path.join(follower_pkg_A, "__init__.py"),
        os.path.join(FOLLOWER_TPL, "__init__.py"),
        lambda: gen_lerobot_follower_init(robot_name),
    )

    # =============================
    # leader B 套件（不带模板字典的简单文件）
    # =============================
    generate_file(
        os.path.join(leader_pkg_B, "__init__.py"),
        os.path.join(LEADER_TPL, "__init__.py"),
        lambda: gen_lerobot_leader_init(robot_name),
    )

    generate_file(
        os.path.join(leader_pkg_B, "calibrate.py"),
        os.path.join(LEADER_TPL, "calibrate.py"),
        gen_leader_calibrate,
    )

    generate_file(
        os.path.join(leader_pkg_B, "config.py"),
        os.path.join(LEADER_TPL, "config.py"),
        lambda: gen_leader_config_py(robot_name, json_data),
    )

    # =============================
    # leader B 套件（使用模板字典的 3 个文件）
    # =============================
    leader_node_ctx = build_leader_node_dict(robot_name, json_data)
    generate_file_with_dict(
        os.path.join(leader_pkg_B, "node.py"),
        os.path.join(LEADER_TPL, "node.py"),
        leader_node_ctx,
        lambda ctx: ""
    )

    leader_teleop_ctx = build_leader_teleoperator_dict(robot_name, json_data)
    generate_file_with_dict(
        os.path.join(leader_pkg_B, "teleoperator.py"),
        os.path.join(LEADER_TPL, "teleoperator.py"),
        leader_teleop_ctx,
        lambda ctx: ""
    )

    leader_status_ctx = build_leader_status_dict(robot_name, json_data)
    generate_file_with_dict(
        os.path.join(leader_pkg_B, "status.py"),
        os.path.join(LEADER_TPL, "status.py"),
        leader_status_ctx,
        lambda ctx: ""
    )

    generate_file(
        os.path.join(leader_pkg_A, "__init__.py"),
        os.path.join(LEADER_TPL, "__init__.py"),
        lambda: gen_lerobot_leader_init(robot_name),
    )


    print("生成完成:")
    print(follower_root)
    print(leader_root)


def main(filename: str):
    """
    filename 是不带 .json 后缀的名称，例如: so101
    """
    json_path = f"../config/{filename}.json"
    generate_ros2_project(json_path, output_root="../../robots")
