from typing import Optional, Protocol

import numpy as np


class Camera(Protocol):
    def connect(self): ...
    def read(self, temporary_color: Optional[str] = None) -> np.ndarray: ...
    def async_read(self) -> np.ndarray: ...
    def disconnect(self): ...
